In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
##Define the vocabulary size

voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
##One Hot Representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[2320, 1582, 2924, 621],
 [2320, 1582, 2924, 9621],
 [2320, 4829, 2924, 4208],
 [4266, 9857, 1093, 5025, 2221],
 [4266, 9857, 1093, 5025, 7739],
 [85, 2320, 6709, 2924, 4828],
 [9103, 5946, 4182, 5025]]

In [9]:
##word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2320 1582 2924  621]
 [   0    0    0    0 2320 1582 2924 9621]
 [   0    0    0    0 2320 4829 2924 4208]
 [   0    0    0 4266 9857 1093 5025 2221]
 [   0    0    0 4266 9857 1093 5025 7739]
 [   0    0    0   85 2320 6709 2924 4828]
 [   0    0    0    0 9103 5946 4182 5025]]


In [12]:
##feature representation
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 2320, 1582, 2924,  621])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 140ms/step


array([[ 0.04143431,  0.00672852, -0.0321032 , -0.02205026,  0.0474969 ,
         0.00423867,  0.03757168,  0.01545123, -0.01127707,  0.02485958],
       [ 0.04143431,  0.00672852, -0.0321032 , -0.02205026,  0.0474969 ,
         0.00423867,  0.03757168,  0.01545123, -0.01127707,  0.02485958],
       [ 0.04143431,  0.00672852, -0.0321032 , -0.02205026,  0.0474969 ,
         0.00423867,  0.03757168,  0.01545123, -0.01127707,  0.02485958],
       [ 0.04143431,  0.00672852, -0.0321032 , -0.02205026,  0.0474969 ,
         0.00423867,  0.03757168,  0.01545123, -0.01127707,  0.02485958],
       [-0.03007131,  0.03915174,  0.0076955 ,  0.02190877,  0.00823871,
         0.03569206, -0.04493543, -0.01923815,  0.03766045, -0.00059398],
       [-0.04094257, -0.04374783, -0.00901274, -0.00532508,  0.0107692 ,
         0.0335494 , -0.01107176, -0.01111246,  0.042241  ,  0.00926582],
       [ 0.02039872, -0.04209776, -0.02336431,  0.0164539 ,  0.03336182,
        -0.04247878,  0.02984687, -0.0433749 